### ISSUE TITLE
Does SSL work on a non standard port?

### ISSUE THREAD

**Issue by henrylaxen** [snapframework/snap-server#136] opened 2020-09-12 21:21 UTC
When I start a snap server on a port other than 443 strange things happen.  On port 444 or 445 when I make a request it just hangs.  On port 888 or 999 I get into an infinite reset loop.  Observe:

```
./nlh -port 8888 --ssl-port=444 --hostname=nadineloveshenry.com 
accessLog: Just log to file "./access.log"
errorLog: Just log to file "./error.log"
locale: Just "en_US"
port: Just 8888
bind: Just "0.0.0.0"
sslport: Just 444
sslbind: Just "0.0.0.0"
sslcert: Just "/etc/letsencrypt/live/nadineloveshenry.com/cert.pem"
sslchaincert: Just False
sslkey: Just "/etc/letsencrypt/live/nadineloveshenry.com/privkey.pem"
unixsocket: Nothing
unixaccessmode: Nothing
compression: Just True
verbose: Just True
defaultTimeout: Just 60
proxyType: Nothing

Listening on http://0.0.0.0:8888
Listening on https://0.0.0.0:444
```

Results in:

```
wget -S http://nadineloveshenry.com:888/dump
--2020-09-12 14:11:22--  http://nadineloveshenry.com:888/dump
Resolving nadineloveshenry.com (nadineloveshenry.com)... 65.111.168.75
Connecting to nadineloveshenry.com (nadineloveshenry.com)|65.111.168.75|:888... connected.
HTTP request sent, awaiting response... Read error (Connection reset by peer) in headers.
Retrying.

```
```
wget -S http://nadineloveshenry.com:444/dump
--2020-09-12 14:14:04--  http://nadineloveshenry.com:444/dump
Resolving nadineloveshenry.com (nadineloveshenry.com)... 65.111.168.75
Connecting to nadineloveshenry.com (nadineloveshenry.com)|65.111.168.75|:444... 

```
and it hangs forever.

No one else is listening to these ports:

```
netstat -nltp                                                                                                          
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 0.0.0.0:443             0.0.0.0:*               LISTEN      14980/nginx: master 
tcp        0      0 127.0.0.1:8001          0.0.0.0:*               LISTEN      14940/./nlh         
tcp        0      0 127.0.0.1:39815         0.0.0.0:*               LISTEN      349/containerd      
tcp        0      0 0.0.0.0:5355            0.0.0.0:*               LISTEN      269/systemd-resolve 
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      14980/nginx: master 
tcp        0      0 127.0.0.53:53           0.0.0.0:*               LISTEN      269/systemd-resolve 
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      347/sshd: /usr/bin/ 
tcp        0      0 0.0.0.0:25              0.0.0.0:*               LISTEN      532/master          
tcp6       0      0 :::5355                 :::*                    LISTEN      269/systemd-resolve 
tcp6       0      0 :::80                   :::*                    LISTEN      14980/nginx: master 
tcp6       0      0 :::22                   :::*                    LISTEN      347/sshd: /usr/bin/ 

```

Is this the expected behaviour?  Any insights would be appreciated.
Best wishes,
Henry Laxen

**Comment by gregorycollins** [comment] 2020-10-30 14:52
I'm not sure what's going on w.r.t port 444 but in your posted example you started the server on 8888 and tried to contact it on 888.

Works for me:
```
[greg@localhost:~/tmp/z]  [10:49AM]
λ /home/greg/git/snapframework/snap-example/dist-newstyle/build/x86_64-linux/ghc-8.6.5/snap-example-0.1.0.0/x/snap-example/build/snap-example/snap-example --ssl-address=127.0.0.1 --ssl-port=7777 --ssl-cert=server.cert --ssl-key=server.key --no-ssl-chain-cert -v
Listening on https://127.0.0.1:7777
```

```
[greg@localhost:~/tmp/z]  [10:50AM]
λ curl -k https://localhost:7777/ 
pong%  
```

Check the error logs and double-check your cert, make sure you build `-threaded`, etc. Closing as "works for me", but --
in trying to reproduce this I found a compile-time bug with our TLS backend on network >= 3, so thanks ;-)

**Closed by gregorycollins** 2020-10-30 14:52 UTC
